// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj99DajTmnsCCEv1oxZIlkXBESD5w0Pg4',
    appId: '1:761120592751:web:a13ba39833d227286a4e9a',
    messagingSenderId: '761120592751',
    projectId: 'e-venture-6d354',
    authDomain: 'e-venture-6d354.firebaseapp.com',
    databaseURL: 'https://e-venture-6d354-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-venture-6d354.firebasestorage.app',
    measurementId: 'G-H3595Y785L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG6ZfaC4KsDPvsNye3nYp6qg2m4CVre9s',
    appId: '1:761120592751:android:9d176c1389d4fbf16a4e9a',
    messagingSenderId: '761120592751',
    projectId: 'e-venture-6d354',
    databaseURL: 'https://e-venture-6d354-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-venture-6d354.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTWzb0MDi1XVAnFxjRxydiYM6c7oFmtHk',
    appId: '1:761120592751:ios:c42ef0a99cafc40f6a4e9a',
    messagingSenderId: '761120592751',
    projectId: 'e-venture-6d354',
    databaseURL: 'https://e-venture-6d354-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-venture-6d354.firebasestorage.app',
    androidClientId: '761120592751-8nn5qb1fuev99erheqovej2v0ijslaf8.apps.googleusercontent.com',
    iosClientId: '761120592751-k4oi5u282q6l776b8f5r1b5t8p93epit.apps.googleusercontent.com',
    iosBundleId: 'com.thethreemasketeers.eventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTWzb0MDi1XVAnFxjRxydiYM6c7oFmtHk',
    appId: '1:761120592751:ios:c42ef0a99cafc40f6a4e9a',
    messagingSenderId: '761120592751',
    projectId: 'e-venture-6d354',
    databaseURL: 'https://e-venture-6d354-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-venture-6d354.firebasestorage.app',
    androidClientId: '761120592751-8nn5qb1fuev99erheqovej2v0ijslaf8.apps.googleusercontent.com',
    iosClientId: '761120592751-k4oi5u282q6l776b8f5r1b5t8p93epit.apps.googleusercontent.com',
    iosBundleId: 'com.thethreemasketeers.eventure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj99DajTmnsCCEv1oxZIlkXBESD5w0Pg4',
    appId: '1:761120592751:web:6d12adb7aec102616a4e9a',
    messagingSenderId: '761120592751',
    projectId: 'e-venture-6d354',
    authDomain: 'e-venture-6d354.firebaseapp.com',
    databaseURL: 'https://e-venture-6d354-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'e-venture-6d354.firebasestorage.app',
    measurementId: 'G-XXLKSC9C9S',
  );

}